#include <iostream>
#include <string>
#include <algorithm>
#include <string>

struct Pokemon {
std::string name;
std::string type;
};
bool compareStrings(std::string& str1, std::string& str2)
{
    if (str1.length() != str2.length())
        return false;

    for (int i = 0; i < str1.length(); ++i) {
        if (tolower(str1[i]) != tolower(str2[i]))
            return false;
    }

    return true;
}
int main(){

Pokemon pokedex[210] = {
    {"Turtwig", "Grass"},
    {"Grotle", "Grass"},
    {"Torterra", "Grass/Ground"},
    {"Chimchar", "Fire"},
    {"Monferno", "Fire/Fighting"},
    {"Infernape", "Fire/Fighting"},
    {"Piplup", "Water"},
    {"Prinplup", "Water"},
    {"Empoleon", "Water/Steel"},
    {"Starly", "Normal/Flying"},
    {"Staravia ", "Normal/Flying"},
    {"Staraptor ", "Normal/Flying"},
    {"Bidoof ", "Normal"},
    {"Bibarel ", "Normal/Water"},
    {"Kricketot ", "Bug"},
    {"Kricketune", "Bug"},
    {"Shinx", "Electric"},
    {"Luxio ", "Electric"},
    {"Luxray ", "Electric"},
    {"Abra", "Psychic"},
    {"Kadabra ", "Psychic"},
    {"Alakazam ", "Psychic"},
    {"Magikarp", "Water"},
    {"Gyrados", "Water"},
    {"Budew", "Grass"},
    {"Roselia", "Grass/Poison"},
    {"Roserade", "Grass/Poison"},
    {"Zubat", "Poison/Flying"},
    {"Golbat", "Poison/Flying"},
    {"Crobat", "Poison/Flying"},
    {"Geodude", "Rock/Ground"},
    {"Graveler", "Rock/Ground"},
    {"Golem", "Rock/Ground"},
    {"Onix", "Rock/Ground"},
    {"Steelix", "Rock/Ground"},
    {"Cranidos", "Rock"},
    {"Rampardos", "Rock"},
    {"Shieldon", "Rock/Steel"},
    {"Bastidon", "Rock/Steel"},
    {"Machop", " FIghting"},
    {"Machoke", "FIghting"},
    {"Machamp", "FIghting"},
    {"Psyduck", "Water"},
    {"Golduck", "Water"},
    {"Burmy", "Bug"},
    {"Wormadam", "Bug/Grass"},
    {"Mothim", "Bug/Flying"},
    {"Wurmple", "Bug"},
    {"Silcoon", "Bug"},
    {"Beautifly", "Bug/Flying"},
    {"Cascoon", "Bug"},
    {"Dustox", "Bug/Poison"},
    {"Combee", "Bug/Flying"},
    {"Vespiqueen", "Bug/Flying"},
    {"Pachirisu", "Electric"},
    {"Buizel", "Water"},
    {"Floatzel", "Water"},
    {"Cherubi", "Grass"},
    {"Cherrim", "Grass"},
    {"Shellos", "Water"},
    {"Gastradon", "Water/Ground"},
    {"Heracross", "Bug/Fighting"},
    {"Aipom", "Normal"},
    {"Ambipom", "Normal"},
    {"Drifloon", "Ghost/Flying"},
    {"Drifblim", "Ghost/Flying"},
    {"Buneary", "Normal"},
    {"Lopunny", "Normal"},
    {"Gastly", "Ghost"},
    {"Haunter", "Ghost/Poison"},
    {"Gengar", "Ghost/Poison"},
    {"Misdreavus", "Ghost"},
    {"Mismagius", "Ghost"},
    {"Murkrow", "Dark/Flying"},
    {"Honchkrow", "Dark/Flying"},
    {"Glameow", "Normal"},
    {"Purugly", "Normal"},
    {"Goldeen", "Water"},
    {"Seaking", "Water"},
    {"Barboach", "Water/Ground"},
    {"Whiscash", "Water/Ground"},
    {"Chingling", "Psychic"},
    {"Chimecho", "Psychic"},
    {"Stunky", "Poison/Dark"},
    {"Skuntank", "Poison/Dark"},
    {"Meditite", "Psychic/Fighting"},
    {"Medicham", "Psychic/Fighting"},
    {"Bronzor", "Psychic/Steel"},
    {"Bronzong", "Psychic/Steel"},
    {"Ponyta", "Fire"},
    {"Rapidash", "Fire"},
    {"Bonsly", "Rock"},
    {"Sudowoodo", "Rock"},
    {"Mime.jr", "Psychic"},
    {"Mr.Mime", "Psychic"},
    {"Happiny", "Normal"},
    {"Chansy", "Normal"},
    {"Blissa", "Normal"},
    {"Cleffa", "Normal"},
    {"Clefairy", "Normal"},
    {"Clefable", "Normal"},
    {"Chatot", "Normal/Flying"},
    {"Pichu", "Electric"},
    {"Pikachu", "Electric"},
    {"Raichu", "Electric"},
    {"Hoothoot", "Normal/Flying"},
    {"Noctowl", "Normal/Flying"},
    {"Spiritomb", "Ghost/Dark"},
    {"Gible", "Dragon"},
    {"Gabite", "Dragon"},
    {"Garchomp", "Dragon/Ground"},
    {"Munchlax", "Normal"},
    {"Snorlax", "Normal"},
    {"Unown", "Psychic"},
    {"Riolu", "Fighting"},
    {"Lucario", "Fighting/Steel"},
    {"Wooper", "Water"},
    {"Quagsire", "Water/Ground"},
    {"Wingull", "Water/Flying"},
    {"Pelipper", "Water/Flying"},
    {"Girafarig", "Normal/Psychic"},
    {"Hippopotas", "Ground"},
    {"Hippowdon", "Ground"},
    {"Azurill", "Normal"},
    {"Marill", "Water"},
    {"Azumarill", "Water"},
    {"Skorupi", "Poison"},
    {"Drapion", "Poison/Dark"},
    {"Croagunk", "Poison/Fighitng"},
    {"Toxicroak", "Poison/Fighting"},
    {"Carnivine", "Grass"},
    {"Remoraid", "Water"},
    {"Octillery", "Water"},
    {"Finneon", "Water"},
    {"Lumineon", "Water"},
    {"Tentacool", "Water/Poison"},
    {"Tentacruel", "Water/Poison"},
    {"Feebas", "Water"},
    {"Milotic", "Water"},
    {"Mantyke", "Water"},
    {"Mantine", "Water"},
    {"Snover", "Ice"},
    {"Abomasnow", "Ice"},
    {"Sneasel", "Ice"},
    {"Weavile", "Ice"},
    {"Uxie", "Psychic"},
    {"Mesprit", "Psychic"},
    {"Azelf", "Psychic"},
    {"Dialga", "Dragon/Steel"},
    {"Palkia", "Dragon/Water"},
    {"Manaphy", "Water"},
    {"Rotom", "Electric"},
    {"Gligor", "Ground/Flying"},
    {"Gliscor", "Ground/Flying"},
    {"Nosepass", "Rock"},
    {"Probopass", "Rock/Steel"},
    {"Ralts", "Psychic"},
    {"Kirlia", "Psychic"},
    {"Gardivoir", "Psychic"},
    {"Gallade", "Psychic/Fighting"},
    {"Lickitung", "Normal"},
    {"Lickilicky", "Normal"},
    {"Eevee", "Normal"},
    {"Vaporeon", "Water"},
    {"Jolteon", "Electric"},
    {"Flareon", "Fire"},
    {"Espeon", "Psychic"},
    {"Umbreon", "Dark"},
    {"Leafeon", "Grass"},
    {"Glacion", "Ice"},
    {"Swablu", "Normal/Flying"},
    {"Altaria", "Dragon/Flying"},
    {"Togepi", "Normal"},
    {"Togetic", "Normal/Flying"},
    {"Togekiss", "Normal/Flying"},
    {"Houndour", "Dark/Fire"},
    {"Houndoom", "Dark/Fire"},
    {"Magnemite", "Electric/Steel"},
    {"Magneton", "Electric/Steel"},
    {"Magnezone", "Electric/Steel"},
    {"Tangela", "Grass"},
    {"Tangrowth", "Grass"},
    {"Yanma", "Bug/Flying"},
    {"Yanmega", "Bug/Flying"},
    {"Tropius", "Grass/Flying"},
    {"Rhyhorn", "Ground/Rock"},
    {"Rhydon", "Ground/Rock"},
    {"Rhyperior", "Ground/Rock"},
    {"Duskull", "Ghost"},
    {"Dusclops", "Ghost"},
    {"Dusknoir", "Ghost"},
    {"Porygon", "Normal"},
    {"Porygon2", "Normal"},
    {"Porygon-Z", "Normal"},
    {"Sycther", "Bug/Flying"},
    {"Scizor", "Bug/Steel"},
    {"Elekid", "Electric"},
    {"Electabuzz", "Electric"},
    {"Electivire", "Electric"},
    {"Magby", "Fire"},
    {"Magmar", "Fire"},
    {"Magmortar", "Fire"},
    {"Swinub", "Ice"},
    {"Piloswine", "Ice/Ground"},
    {"Mamoswine", "Ice/Ground"},
    {"Snorunt", "Ice"},
    {"Glalie", "Ice"},
    {"Froslass", "Ice/Ghost"},
    {"Absol", "Dark"},
    {"Giratina", "Ghost/Dragon"}
};


std::cout << "Enter a Gen 4 Pokemon: ";
std::string userInput;
std::getline(std::cin, userInput);

for (int i = 0; i < 210; i++) {
    if (compareStrings(pokedex[i].name, userInput)) {
        std::cout << "#" << i + 1 << " Name: " << pokedex[i].name << " Type: " << pokedex[i].type;
    }
}


return 0;
}
